CREATE TABLE "ROOM" (
    "ID" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CAPACITY" INTEGER NOT NULL,
    "ROOMNUMBER" VARCHAR(31) NOT NULL,
    "DOUBLEBED" BOOLEAN NOT NULL,
    "NOTE" VARCHAR(255)
);

CREATE TABLE "GUEST" (
    "ID" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ROOMID" INT REFERENCES ROOM (ID),
    "NAME" VARCHAR(255),
    "ADDRESS" VARCHAR(255),
    "PHONE" VARCHAR(31),
    "BIRTHDATE" DATE
);